name: Site

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: site
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ruby

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: make install

      - name: Build site
        run: make build
